# Generated by Django 4.1.3 on 2024-10-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
